### ISSUE TITLE
Recipe Book does not show ingredient NBT data

### ISSUE THREAD

**Issue by MrTalk** [Siphalor/nbt-crafting#79] opened 2021-06-21 18:46 UTC
This effects things like:
Item Names
Item Lore
Item Textures (If you are using CustomModelData)
Player Skulls

**Comment by Siphalor** [comment] 2021-08-14 11:02
hm, since you didn't use the bug issue template I'm gonna have to ask the question manually:

Which version of Minecraft?
Which version of Nbt Crafting?
Singleplayer or Multiplayer? If the latter, is the mod installed on the client side?

Can you give me an example recipe so that I can easily reproduce the issue under the given circumstances?

**Comment by Siphalor** [comment] 2022-02-19 16:22
Since there hasn't been any activity on this, I'm gonna close this issue.

If you can reproduce this issue again let me know with the information I asked for :)

**Closed as completed by Siphalor** 2022-02-19 16:22 UTC
Labels: bug, question
